general:
  thread_count: 12
  use_gpu: true
  save_figures: false

search:
  target_ms1_tolerance: 0
  target_ms2_tolerance: 0
  target_rt_tolerance: 0.0
  target_mobility_tolerance: 0.0
  extraction_backend: rust

fdr:
  fdr: 0.01
  group_level: proteins
  inference_strategy: heuristic

search_output:
  file_format: tsv
  precursor_level_lfq: true
  peptide_level_lfq: true
